export const skills = [
    "React",
    "React Hooks",
    "React Router",
    "Redux",
    "Redux Toolkit",
    "Redux-Saga",
    "Working with API (fetch, axios)",
    "Promise, Async/Await",
    "Error Handling",
    "JavaScript: ES6+",
    "Immutability",
    "CSS BEM convention",
    "CSS Flexbox",
    "CSS Grid",
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "Git",
    "NPM"
];