export const skills = [
    "Semantic & accessible HTML",
    "CSS BEM convention",
    "CSS Flexbox",
    "CSS Grid",
    "Styled Components",
    "Responsive Web Design",
    "JavaScript: ES6+",
    "TypeScript",
    "React",
    "React Hooks",
    "React Router",
    "TanStack Query",
    "Redux",
    "Redux Toolkit",
    "Redux-Saga",
    "Working with API (fetch, axios)",
    "Promise, Async/Await",
    "Error Handling",
    "Immutability",
    "Git",
    "NPM",
    "GitHub Pull Requests & Review",
    "Trello"
];