export const lightTheme = {
    colors: {
        bodyBackground: "#FBFBFE",
        caption: "#6E7E91",
        header: "#252525",
        aboutMeContent: "#6E7E91",
        switchBackground: "#E5E5E5",
        switchBorder: "#6E7E91",
        switchDisc: "#6E7E91",
        switchSun: "#FFFFFF",
        headerBorder: "#D1D5DA4D",
        sectionBackground: "#FFFFFF",
        sectionShadowTop: "#090A3308",
        sectionShadowBottom: "#090A3305",
        sectionContent: "#6E7E91",
        buttonContent: "#FFFFFF",
        buttonBackground: "#0366D6",
        buttonBorder: "#D1D5DA4D",
        projectHeader: "#0366D6",
        projectDescription: "#6E7E91",
        projectLink: "#0366D6",
        linkTransparent: "#0365d619",
        projectBorder: "#D1D5DA4D",
        afterHovering: "#0366D6",
        afterHoveringTransparent: "#0366D633",
        errorHeader: "#252525",
        loadingText: "#252525",
        mail: "#252525",
        footerContent: "#252525",
    },
};

export const darkTheme = {
    colors: {
        bodyBackground: "#252525",
        caption: "#FFFFFF",
        header: "#FFFFFF",
        aboutMeContent: "#FFFFFF",
        switchBackground: "#6E6E6E",
        switchBorder: "#FFFFFF",
        switchDisc: "#FFFFFF",
        switchSun: "#252525",
        headerBorder: "#D1D5DA1A",
        sectionBackground: "#363636B8",
        sectionShadowTop: "#090A3308",
        sectionShadowBottom: "#090A3305",
        sectionContent: "#FFFFFF",
        buttonContent: "#FFFFFF",
        buttonBackground: "#2188FF",
        buttonBorder: "#D1D5DA4D",
        projectHeader: "#FFFFFF",
        projectDescription: "#FFFFFF",
        projectLink: "#2188FF",
        linkTransparent: "#0365d650",
        projectBorder: "#D1D5DA1A",
        afterHovering: "#2188FF",
        afterHoveringTransparent: "#0366D680",
        errorHeader: "#FFFFFF",
        loadingText: "#FFFFFF",
        mail: "#FFFFFF",
        footerContent: "#FFFFFF",
        icon: "#FFFFFF",
    },
};