export const lightTheme = {
    colors: {
        bodyBackground: "#FBFBFE",
        bodyText: "#252525",
        caption: "#6E7E91",
        header: "#252525",
        aboutMeContent: "#6E7E91",
        border: "#D1D5DA4D",
        sectionBackground: "#FFFFFF",
        sectionShadowTop: "#090A3308",
        sectionShadowBottom: "#090A3305",
        sectionContent: "#6E7E91",
        buttonContent: "#FFFFFF",
        linkContainer: "#0366D6",
        projectHeader: "#0366D6",
        projectDescription: "#6E7E91",
        link: "#0366D6",
        afterHovering: "#0366D6",
        afterHoveringTransparent: "#0366D633",
    },
}

export const darkTheme = {
    colors: {
        bodyBackground: "#252525",
        bodyText: "#FFFFFF",
        caption: "#FFFFFF",
        header: "#FFFFFF",
        aboutMeContent: "#FFFFFF",
        border: "#D1D5DA4D",
        sectionBackground: "#363636B8",
        sectionShadowTop: "#090A3308",
        sectionShadowBottom: "#090A3305",
        sectionContent: "#FFFFFF",
        buttonContent: "#FFFFFF",
        linkContainer: "#2188FF",
        projectHeader: "#FFFFFF",
        projectDescription: "#FFFFFF",
        link: "#2188FF",
        afterHovering: "#2188FF",
        icon: "#FFFFFF",
        afterHoveringTransparent: "#0366D680",
    },
}